server:
  port: 8080

resilience4j.circuitbreaker:
  instances:
    downstreamCircuit:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 2

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG

springdoc:
  swagger-ui:
    path: /docs
